### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by wenhuizhang** [lzto/pex#1]
Hi, Tong:
If I would like to test PeX against my patched version of v5.3, where should I get started please?
Which lines should I add to my ***config*** and ***makefile*** please?
By the way, I have a stacked security module, and would like to constrain the test to the stacked modules with their preserved orders, and not skip tests on those code which are not gonnar be compiled into the ramfs file.

**Comment by lzto** [comment]
sounds like you are trying to generate the kernel bytecode.
I would suggest using wllvm to build the kernel. 
to configure your kernel, use make menuconfig
please refer to this link for more details https://github.com/lzto/pex#vmlinuxbc
