### ISSUE TITLE
Gets stuck with LSM gating function

### ISSUE THREAD

**Issue by madil27** [lzto/pex#3]
I am running to tool to analyze the permission checks within Linux Kernels. Using the `build.sh` file I was successfully able to generate `libgatlin.so` and then ran the opt command to conduct the analysis of the vmlinux.bc file of the kernel generated via WLLVM. The tool seems to work fine for CAP and DAC gating functions, however, with the LSM gating function, it gets stuck for an indefinite amount of time after printing out the KMI stats and the statement "Collect all permission-checked variables and functions"

![Screen Shot 2021-03-23 at 2 23 31 PM](https://user-images.githubusercontent.com/42498361/112206427-e920a580-8be3-11eb-91c6-bcb1ef675d04.png)

I have ran the tool for more than 24 hours, so time overhead doesn't seem to be an issue. Moreover, the `top` command shows 5% memory consumption and 100% CPU consumption by the process, so memory does not seem to be an issue as well. 

Would really appreciate any help in this regard! I have tried different kernels (5.3, 4.14, 4.18) and the same issue persists in all of them with the LSM gating function. 

Environment:
Ubuntu 18.04
LLVM-9/Clang-9/OPT-9
Kernels tested: 4.14, 4.18, 5.3 (with deconfig)

**Comment by lzto** [comment]
Hi, 
This can happen when it stuck with some library functions  -- you can try to add the library function to the skip list and try again.
- Tong

**Comment by madil27** [comment]
Hi, 
Thank you for the quick response!!

Was able to resolve the issue with the addition of three more skip functions:
`pointer`
 `finish_task_switch`
 `__free_irq`

**Comment by lzto** [comment]
Sounds good. Let me know if you have other questions.

**Comment by kunzeng-ch** [comment]
Hello, I want to use the tool to analysis the system call graph of Linux 4.18.5.When I run ./build.sh build, I got the error: make: *** No targets specified and no makefile found.  Stop. I need your help, please!

**Comment by lzto** [comment]
Hi @zengshaokun , looks like Makefile is not generated.
Please check if cmake is installed on your system.

**Comment by kunzeng-ch** [comment]
Hi, I have run ./build.sh tag and ./build.sh build successfully. However, when I run "make CC=wllvm", I got the error: arch/x86/Makefile:184: *** Compiler lacks asm-goto support..  Stop. I tried the solutions of "https://unix.stackexchange.com/questions/456767/make-menuconfig-error-while-trying-to-build-kernel"，the error still exists. My configuration environment is Linux version 4.18.5-041805-generic (kernel@kathleen) (gcc version 8.2.0 (Ubuntu 8.2.0-4ubuntu1)) #201808241320 SMP Fri Aug 24 13:22:12 UTC 2018. The version of LLVM is 10.0.1. Can you help me solve the problem?

**Comment by kunzeng-ch** [comment]
Can you share vmlinux.bc you generated with me?

**Comment by lzto** [comment]
@zengshaokun , which kernel version are you trying to compile?
There are some known compatibility issues with older versions of linux kernel and clang.

Could you please open another issue and discuss since this one is closed.

**Comment by kunzeng-ch** [comment]
Thank you for your answer.I had solved the problem : arch/x86/Makefile:184: *** Compiler lacks asm-goto support.. Stop. When I run the commond "opt \
    -analyze \
    -load=build/gatlin/libgatlin.so \
    -gatlin \
    -gating=cap \
    -ccv=0 -ccf=1 -cct=0\
    -ccvv=0 -ccfv=0 -cctv=0\
    -cvf=0 \
    -skipfun=skip.fun \
    -skipvar=skip.var \
    -lsmhook=lsm.hook \
    -prt-good=0 -prt-bad=1 -prt-ign=0 \
    -stats \
    vmlinux.bc \
    -o /dev/null 2>&1 | tee log", it seems to last a long time. How can I determine whether this command is running normally? I didn't see any files generated by it, but when viewed with top, its process occupies nearly 100% of the cpu
