### ISSUE TITLE
call graph generation

### ISSUE THREAD

**Issue by meweez** [lzto/pex#4]
hello,
Is it possible to use this code for call graph generation for codes except for Linux?
Thanks

**Comment by lzto** [comment]
Hi,
PeX in its current form is specialized for linux kernel
 -- however, with some(minor) modifications it can handle other code as well.
Most of the code can be reused for other analysis.
- Tong

**Comment by lzto** [comment]
I am closing this issue for now, please reopen if you have more questions.
