### ISSUE TITLE
How can I determine whether pex is running normally?

### ISSUE THREAD

**Issue by kunzeng-ch** [lzto/pex#5]
Thank you for your answer.I had solved the problem "arch/x86/Makefile:184: *** Compiler lacks asm-goto support. Stop"When I run the commond "opt
-analyze
-load=build/gatlin/libgatlin.so
-gatlin
-gating=cap
-ccv=0 -ccf=1 -cct=0
-ccvv=0 -ccfv=0 -cctv=0
-cvf=0
-skipfun=skip.fun
-skipvar=skip.var
-lsmhook=lsm.hook
-prt-good=0 -prt-bad=1 -prt-ign=0
-stats
vmlinux.bc
-o /dev/null 2>&1 | tee log", it seems to last a long time. How can I determine whether this command is running normally? I didn't see any files generated by it, but when viewed with the commond of top, its process occupies nearly 100% of the cpu. I have been running the command for almost a day and night.

**Comment by lzto** [comment]
Are skip.fun, skip.var and lsm.hook in the same directory where you run the command?

**Comment by kunzeng-ch** [comment]
Yes, They are all under the path of /home/pex-master/gatlin/. I run the command under /home/pex-master

**Comment by kunzeng-ch** [comment]
I want to know how long it will take for this pex to run the above command normally before it can be executed.

**Comment by kunzeng-ch** [comment]
Excuse me, can you generate a flowchart of each system call in the kernel code for this project? For example, for the system call: “write”, through this graph, can I find out which functions in the kernel code use the system call "write" through one or more levels?

**Comment by kunzeng-ch** [comment]
Thank you very much for taking the time to reply to my question. I didn't talk to you before. Now the environment where I run pex is ubuntu16.04, and the kernel is 5.10.5. I tried it on kernel version 4.18.5, but I can’t generate the vmlinux.bc file, but it can be generated on 5.10.5.

**Comment by lzto** [comment]
Depending on the machine but it should take less than an hour. Have your skip functions(some library functions) well defined in skip.fun so that pex won't spend a lot of time exploring them. The default one should work for many cases but you may find there are still some other functions you need to put in this list.
In my case it can finish execution under 20min YMMV.

For generating call graph you will need to take a look at 1) direct call, the callee can be get from the CallInst itself using getCalledValue(), 2) indirect call, take a look at resolve_indirect_callee function to learn how to get callee for indirect call and you may need to write your own tool to generate the image.

**Comment by kunzeng-ch** [comment]
OK！Thank you very much for taking the time to help me solve my question carefully. I understand what you mean. I would like to ask if the kernel version is 4.18.5 or 5.10, and the llvm and clang versions are 10.0.1, is there a problem with this environment configuration? In other words, do you recommend me to use 4.18.5 or 5.10 for the kernel version?

**Comment by kunzeng-ch** [comment]
I just ran the command :
opt \
    -analyze \
    -load=build/gatlin/libgatlin.so \
    -gatlin \
    -gating=cap \
    -ccv=0 -ccf=1 -cct=0\
    -ccvv=0 -ccfv=0 -cctv=0\
    -cvf=0 \
    -skipfun=skip.fun \
    -skipvar=skip.var \
    -lsmhook=lsm.hook \
    -prt-good=0 -prt-bad=1 -prt-ign=0 \
    -stats \
    vmlinux.bc \
    -o /dev/null 2>&1 | tee log.
Have this command skip the functions(some library functions), right? When I ran the comman, the printed result always shows  "Add call<direct> drv_stop_ap use @
 cause:Process Stack:
0 restricted_pointer
1 pointer
2 vsnprintf
3 slab_err
4 check_slab
5 alloc_debug_processing
6 ___slab_alloc
7 __kmalloc_node_track_caller
8 __alloc_skb
9 nl80211_frame_tx_status
10 cfg80211_control_port_tx_status
11 ieee80211_report_used_skb
12 ieee80211_purge_tx_queue
13 ieee80211_tx_frags
14 __ieee80211_tx
15 ieee80211_tx
16 ieee80211_xmit
17 __ieee80211_tx_skb_tid_band
18 ieee80211_send_delba
19 ___ieee80211_stop_rx_ba_session
20 ieee80211_sta_tear_down_BA_sessions
21 ieee80211_key_replace
22 ieee80211_free_sta_keys
23 __sta_info_destroy_part2
24 __sta_info_flush
25 ieee80211_stop_ap" repeatedly. Is this process stuck?

**Comment by lzto** [comment]
which pex version are you using? It doesn't look like the latest.

**Comment by kunzeng-ch** [comment]
What I downloaded is the pex by the url: https://github.com/lzto/pex

**Comment by lzto** [comment]
code should print  ```Add call<direct> ``` or  ```Add call<indirect>```instead of ```Add call xxx```
maybe the your post is not showing correctly if you were using the latest version

anyway can you check the log and see if you can find something like

```
Load supplimental files...
    - Skip function list, total: xxx
```

**Comment by kunzeng-ch** [comment]
Hello! I checked the log, "Load supplimental files..." is there, but there is no the sentence: "Skip function list, total: xxx". When the program runs here: 
"# of indirect call sites: 19201
# resolved by KMI:17553 91%
#     - KMI:7386 38%
#     - DKMI:3067 15%
# (total target) of callee:49869
# undefined-found-m : 5850 30%
# undefined-udf-m : 1250 6%
# fpara(KMI can not handle, try SVF?): 531 2%
# global fptr(try SVF?): 123 0%
# cast fptr(try SVF?): 0 0%
# call use container_of(), high level type info stripped: 909 4%
# unknown pattern:85 0%
STOP WATCH[0]: 8752.895000 ms
Collect all permission-checked variables and functions"
, it seems to be stuck, and no tasks are printed out.

**Comment by lzto** [comment]
I'd suggest copy ``skip.fun, skip.var, lsm.hook`` to your working directory and try again

**Comment by kunzeng-ch** [comment]
I copied skip.fun, skip.var, lsm.hook to my working directory and try again.
the sentences :"Load supplimental files... - Skip function list, total: xxx" were generated, but they are still stuck here:
------ KMI STATISTICS ------
# of indirect call sites: 19201
# resolved by KMI:17553 91%
#     - KMI:7386 38%
#     - DKMI:3067 15%
# (total target) of callee:49754
# undefined-found-m : 5850 30%
# undefined-udf-m : 1250 6%
# fpara(KMI can not handle, try SVF?): 531 2%
# global fptr(try SVF?): 123 0%
# cast fptr(try SVF?): 0 0%
# call use container_of(), high level type info stripped: 909 4%
# unknown pattern:85 0%
STOP WATCH[0]: 8705.149000 ms
Collect all permission-checked variables and functions

**Comment by lzto** [comment]
Is it still stuck?

**Comment by kunzeng-ch** [comment]
No. This command had been executed and the following results are printed.
--- DONE! ---
------------STATISTICS---------------
    48575 : Functions greeted
    1458 : External functions
    0 : Discovered Path
    0 : Matched Path
    139785 : Good Path
    8066 : Bad Path
    159752 : Ignored Path
    0 : Path Unable to Resolve
    0 : Resolved CallSite Using Function Pointer
    1797 : Critical Functions
    365 : Critical Variables
    0 : # of times max depth for forward analysis hit
    0 : # of times max depth for backward analysis hit
    32892 : Critical Function Pointer Unable to Resolve, Collect Pass
    11432 : Critical Function Pointer Resolved, Collect Pass
    14348 : Critical Functions used by non CallInst
    87873 : Critical Functions used by static assignment
    827 : # of times indirect call site matched with critical functions
    76737 : # of times indirect call site failed to match with critical functions
    0 : found capability check inside call using function ptr

    284 : number of critical function skipped(uniq)
Does this result mean that the operation is successful?

**Comment by kunzeng-ch** [comment]
However, when I run the test.sh file under the test folder, the following error appears。
”opt: symbol lookup error: /home/pex-master/build/gatlin/libgatlin.so: undefined symbol: _ZN4llvm21DominanceFrontierBaseINS_10BasicBlockELb0EEC2Ev“
I have changed the libgatlin.so file to the corresponding file generated by myself.

**Comment by lzto** [comment]
Do you have multiple versions of llvm installed in the system?
Try specify the version with ```opt-10``` to see if that makes a difference.

**Comment by kunzeng-ch** [comment]
I only installed the llvm version 10.0.1, and I ran the command: opt --version showed that the llvm version is 10.0.1.
LLVM (http://llvm.org/):
  LLVM version 10.0.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: core2

**Comment by lzto** [comment]
I could not reproduce the 2nd issue.
It looks like version mismatch but I can't tell for sure.

**Comment by lzto** [comment]
> No. This command had been executed and the following results are printed. --- DONE! --- ------------STATISTICS--------------- 48575 : Functions greeted 1458 : External functions 0 : Discovered Path 0 : Matched Path 139785 : Good Path 8066 : Bad Path 159752 : Ignored Path 0 : Path Unable to Resolve 0 : Resolved CallSite Using Function Pointer 1797 : Critical Functions 365 : Critical Variables 0 : # of times max depth for forward analysis hit 0 : # of times max depth for backward analysis hit 32892 : Critical Function Pointer Unable to Resolve, Collect Pass 11432 : Critical Function Pointer Resolved, Collect Pass 14348 : Critical Functions used by non CallInst 87873 : Critical Functions used by static assignment 827 : # of times indirect call site matched with critical functions 76737 : # of times indirect call site failed to match with critical functions 0 : found capability check inside call using function ptr
> 
> ```
> 284 : number of critical function skipped(uniq)
> ```
> 
> Does this result mean that the operation is successful?

yes it is

**Comment by kunzeng-ch** [comment]
OK! Thank you for your answer! Then I will carefully analyze the cause of the error by myself.

**Comment by kunzeng-ch** [comment]
Hello! I remembered one thing. During the operation, the following message appeared. Is this normal?
Use:
=BAD PATH=
Call Stack:
0 __do_sys_exit_group
1 __se_sys_exit_group
2 __x64_sys_exit_group
-------------
Path:
Function:__x64_sys_exit_group
 %2 = getelementptr inbounds %struct.pt_regs, %struct.pt_regs* %0, i64 0, i32 14
 %3 = load i64, i64* %2, align 8
 tail call fastcc void @__se_sys_exit_group(i64 %3) #75
Function:__se_sys_exit_group
 %2 = trunc i64 %0 to i32
 tail call fastcc void @__do_sys_exit_group(i32 %2) #75
Function:__do_sys_exit_group
 %2 = shl i32 %0, 8
 %3 = and i32 %2, 65280
 tail call void @do_group_exit(i32 %3) #75
-------------
Good: 2 Bad: 2 Ignored: 0
Check Use of Function:fib_release_info
Check Use of Function:udpv6_exit
Check Use of Function:user_disable_single_step
Check Use of Function:__skb_recv_udp

**Comment by lzto** [comment]
yes it is. This message means a potential bug is discovered.

**Comment by kunzeng-ch** [comment]
OK! Thank you very much!

**Comment by kunzeng-ch** [comment]
Hello! Can you share the KIRIN with me?

**Comment by lzto** [comment]
KIRIN is built in PeX. Please checkout the paper.

**Comment by kunzeng-ch** [comment]
Excuse me, what does this call stack mean, can you tell me?
Call Stack:
0 _xfs_log_force fs/xfs/xfs_log_priv.h:561:2 @[ fs/xfs/xfs_log.c:3399:3 ]
1 xfs_log_force_umount fs/xfs/xfs_log.c:4035:3
2 xfs_do_force_shutdown fs/xfs/xfs_fsops.c:973:6
3 xfs_log_commit_cil fs/xfs/xfs_log_cil.c:501:3 @[ fs/xfs/xfs_log_cil.c:1009:2 ]
4 __xfs_trans_commit fs/xfs/xfs_trans.c:937:2
5 xfs_trans_commit fs/xfs/xfs_trans.c:981:9
6 xfs_vn_update_time fs/xfs/xfs_iops.c:1074:9
It means that 6 calls 5, then 5 calls 4, and finally calls 0. Is that true?

**Comment by lzto** [comment]
Yes, you can verify it by looking at the source code.

**Comment by kunzeng-ch** [comment]
OK! I had verified it by checking the source code of kernel. Thank you very much!

**Comment by lzto** [comment]
I am marking this issue solved. Pleas reopen if issue persists.
Thanks,
 -- Tong
